services:
  - type: web
    name: data-warehouse-cdmx-dashboard
    runtime: docker
    plan: free
    dockerfilePath: ./dashboard/Dockerfile.render
    dockerContext: .
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: data-warehouse-cdmx-db
          property: connectionString
      - key: DW_AUTO_INIT
        value: "true"

databases:
  - name: data-warehouse-cdmx-db
    plan: free
    databaseName: data_warehouse
    user: data_warehouse_user
